[workspace]
members = [
    "ad-server",
    "synchronizer",
    "app",
    "common"]
resolver = "3"

[workspace.dependencies]
alloy = { version = "1.0.13", features = [
    "eips",
    "full",
    "json-rpc",
    "rpc-client",
    "rpc-types-beacon"
] }
tokio = {version="1.45", features = ["rt-multi-thread", "macros"]}
plonky2 = { git = "https://github.com/0xPARC/plonky2.git", rev = "767a098d89b8d50d8aacfdce0c0a7222e8760d37" }
pod2 = { git="https://github.com/0xPARC/pod2", rev = "1d14338351029a4c2cc0d46914e3bcd580e1b92f", default-features = false, features = ["backend_plonky2", "disk_cache", "zk"]}
env_logger = { version = "0.11" }
log = { version = "0.4.14", features = ["kv_unstable"] }
dotenvy = "0.15.7"
anyhow = "1.0.56"
sqlx = { version="0.8.6", features = ["sqlite", "chrono", "runtime-tokio"] }


# [patch."https://github.com/0xPARC/pod2"]
# pod2 = { git="https://github.com/0xPARC/pod2?rev=main", rev = "021ccaeaa8693dec7b9538aad03931c85a83c191" }
