[workspace]
members = [
    "ad-server",
    "synchronizer",
    "app"
]
resolver = "3"

[workspace.dependencies]
alloy = { version = "1.0.13", features = [
    "eips",
    "full",
    "json-rpc",
    "rpc-client",
] }
tokio = {version="1.45", features = ["rt-multi-thread", "macros"]}
pod2 = { git="https://github.com/0xPARC/pod2", rev = "3d098c3ce6c89dbf3c26ef06e9cd4e8b8a484f1a", default-features = false, features = ["backend_plonky2", "disk_cache", "zk"]}
env_logger = "0.11"
