[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
sqlx = { workspace = true }
log = { workspace = true }
dotenvy = { workspace = true }
warp = { workspace = true }
