[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
sqlx = { workspace = true }
log = { workspace = true }
dotenvy = { workspace = true }
warp = { workspace = true }
pod2 = { workspace = true }
plonky2 = { workspace = true }
itertools = "0.14.0"

[dev-dependencies]
app = { path = "../app" }
ad-server = { path = "../ad-server" }
